### ISSUE TITLE
About using mobile device as AP

### ISSUE THREAD

**Issue by kingsj0405** [googlesamples/android-WifiRttScan#1]
Hello.
I'm new in indoor positioning and I want to test `WifiRTTScan`.
Thank you for nice sample!

I have a issue with using this application demo but failing to get answer from other community.

I have Google Pixel 2 which supports 802.11mc(WiFi RTT) with Android Pie(9).
But because there is no APs support 802.11mc(WiFi RTT) around me, I try to use my mobile devices as AP.
My phone is `Galaxy Note 9` which has `Qualcomm Snapdragon 845`.

Is this possible?
Thank you.

**Comment by codingjeremy** [comment]
I don't believe so. You will need to pick up a Access Point that supports it. Have a look at Compulab. They have the [filet2](https://fit-iot.com/web/products/fitlet2/) or the [Wild](https://fit-iot.com/web/products/wild/). 

There should be more options coming out in the not too distant future.
